export const COUNTER_INCREMENT = "INCREMENT";
export const COUNTER_DECREMENT = "DECREMENT";
export const COUNTER_RESET = "RESET";

export const NUMBER_GUESS = "NUMBER_GUESS"
export const SET_FEEDBACK_MESSAGE = "SET_FEEDBACK_MESSAGE"